// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  firebase: {
    projectId: 'ejercicioapp-d2bcb',
    appId: '1:1055913565040:web:4bcf86a8c9031746110db5',
    storageBucket: 'ejercicioapp-d2bcb.appspot.com',
    locationId: 'us-central',
    apiKey: 'AIzaSyDEuLZREsb_rxLFDyfvUGsPnwfEts7iwak',
    authDomain: 'ejercicioapp-d2bcb.firebaseapp.com',
    messagingSenderId: '1055913565040',
  },
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'es-ES',
  supportedLanguages: ['es-ES'],
};
